//! Zero-allocation text formatters for generated byte streams.
//!
//! Formats byte arrays into ASCII Decimal (`int`), Bitstream (`bits`), Hexadecimal (`hex`),
//! and Normalized Floats (`float`).

use super::traits::OutputFormat;

/// Formats a single byte into decimal ASCII with newline (e.g. `123\n`) writing to `dest`.
/// Returns the number of bytes written (2 to 4 bytes).
#[inline]
pub fn format_byte_int(val: u8, dest: &mut [u8]) -> usize {
    if dest.len() < 4 {
        return 0;
    }
    if val >= 100 {
        dest[0] = b'0' + (val / 100);
        dest[1] = b'0' + ((val / 10) % 10);
        dest[2] = b'0' + (val % 10);
        dest[3] = b'\n';
        4
    } else if val >= 10 {
        dest[0] = b'0' + (val / 10);
        dest[1] = b'0' + (val % 10);
        dest[2] = b'\n';
        3
    } else {
        dest[0] = b'0' + val;
        dest[1] = b'\n';
        2
    }
}

/// Formats a single byte into 8 ASCII bits (`0` and `1`).
#[inline]
pub fn format_byte_bits(val: u8, dest: &mut [u8]) -> usize {
    if dest.len() < 8 {
        return 0;
    }
    for (shift, slot) in dest[..8].iter_mut().enumerate() {
        let bit = (val >> (7 - shift)) & 1;
        *slot = b'0' + bit;
    }
    8
}

/// Formats a single byte into 2 lowercase hexadecimal ASCII characters.
#[inline]
pub fn format_byte_hex(val: u8, dest: &mut [u8]) -> usize {
    const HEX_CHARS: &[u8; 16] = b"0123456789abcdef";
    if dest.len() < 2 {
        return 0;
    }
    dest[0] = HEX_CHARS[(val >> 4) as usize];
    dest[1] = HEX_CHARS[(val & 0x0F) as usize];
    2
}

/// Formats a single byte normalized to `[0.0, 1.0)` as `"0.xxxxxx\n"`.
#[inline]
pub fn format_byte_float(val: u8, dest: &mut [u8]) -> usize {
    // val / 255.0 as fixed precision 6 decimal places: int val from 0 to 1_000_000
    if dest.len() < 10 {
        return 0;
    }
    let frac = (val as u32 * 1_000_000 + 127) / 255;
    dest[0] = b'0';
    dest[1] = b'.';
    dest[2] = b'0' + ((frac / 100_000) % 10) as u8;
    dest[3] = b'0' + ((frac / 10_000) % 10) as u8;
    dest[4] = b'0' + ((frac / 1000) % 10) as u8;
    dest[5] = b'0' + ((frac / 100) % 10) as u8;
    dest[6] = b'0' + ((frac / 10) % 10) as u8;
    dest[7] = b'0' + (frac % 10) as u8;
    dest[8] = b'\n';
    9
}

/// Formats a raw byte slice into `dest` according to `format`.
/// Returns the number of formatted bytes written.
pub fn format_stream(raw: &[u8], format: OutputFormat, dest: &mut [u8]) -> usize {
    match format {
        OutputFormat::Binary => {
            let count = raw.len().min(dest.len());
            dest[..count].copy_from_slice(&raw[..count]);
            count
        }
        OutputFormat::AsciiInt => {
            let mut out_idx = 0;
            for &b in raw {
                if out_idx + 4 > dest.len() {
                    break;
                }
                let written = format_byte_int(b, &mut dest[out_idx..]);
                out_idx += written;
            }
            out_idx
        }
        OutputFormat::AsciiBits => {
            let mut out_idx = 0;
            for &b in raw {
                if out_idx + 8 > dest.len() {
                    break;
                }
                let written = format_byte_bits(b, &mut dest[out_idx..]);
                out_idx += written;
            }
            out_idx
        }
        OutputFormat::Hex => {
            let mut out_idx = 0;
            for &b in raw {
                if out_idx + 2 > dest.len() {
                    break;
                }
                let written = format_byte_hex(b, &mut dest[out_idx..]);
                out_idx += written;
            }
            out_idx
        }
        OutputFormat::Float => {
            let mut out_idx = 0;
            for &b in raw {
                if out_idx + 9 > dest.len() {
                    break;
                }
                let written = format_byte_float(b, &mut dest[out_idx..]);
                out_idx += written;
            }
            out_idx
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_formatters() {
        let raw = [0u8, 127u8, 255u8];
        let mut buf = [0u8; 64];

        // Binary
        let n = format_stream(&raw, OutputFormat::Binary, &mut buf);
        assert_eq!(&buf[..n], &raw);

        // AsciiInt
        let n = format_stream(&raw, OutputFormat::AsciiInt, &mut buf);
        assert_eq!(&buf[..n], b"0\n127\n255\n");

        // AsciiBits
        let n = format_stream(&raw, OutputFormat::AsciiBits, &mut buf);
        assert_eq!(&buf[..n], b"000000000111111111111111");

        // Hex
        let n = format_stream(&raw, OutputFormat::Hex, &mut buf);
        assert_eq!(&buf[..n], b"007fff");

        // Float
        let n = format_stream(&raw, OutputFormat::Float, &mut buf);
        assert!(n > 0);
    }
}
