//! Common traits and definitions for byte stream generators.

/// Common trait implemented by all `#![no_std]` byte stream generators.
pub trait ByteGenerator {
    /// Generates the next byte in the stream.
    fn next_byte(&mut self) -> u8;

    /// Fills the destination slice with generated bytes.
    fn fill_bytes(&mut self, dest: &mut [u8]) {
        for b in dest.iter_mut() {
            *b = self.next_byte();
        }
    }

    /// Resets the generator state back to its initial configuration.
    fn reset(&mut self);
}

/// Supported generator types for CLI and WASM C-ABI.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum GeneratorType {
    Sequence = 0,
    Fixed = 1,
    Lfsr = 2,
    DeBruijn = 3,
    Lcg = 4,
    Xoshiro = 5,
    Gaussian = 6,
    Poisson = 7,
    AesCtrDrbg = 8,
    Sha256Drbg = 9,
    ChaCha20 = 10,
}

impl GeneratorType {
    pub fn from_u32(val: u32) -> Option<Self> {
        match val {
            0 => Some(Self::Sequence),
            1 => Some(Self::Fixed),
            2 => Some(Self::Lfsr),
            3 => Some(Self::DeBruijn),
            4 => Some(Self::Lcg),
            5 => Some(Self::Xoshiro),
            6 => Some(Self::Gaussian),
            7 => Some(Self::Poisson),
            8 => Some(Self::AesCtrDrbg),
            9 => Some(Self::Sha256Drbg),
            10 => Some(Self::ChaCha20),
            _ => None,
        }
    }
}

/// Output text formatting modes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum OutputFormat {
    Binary = 0,
    AsciiInt = 1,
    AsciiBits = 2,
    Hex = 3,
    Float = 4,
}

impl OutputFormat {
    pub fn from_u32(val: u32) -> Option<Self> {
        match val {
            0 => Some(Self::Binary),
            1 => Some(Self::AsciiInt),
            2 => Some(Self::AsciiBits),
            3 => Some(Self::Hex),
            4 => Some(Self::Float),
            _ => None,
        }
    }
}
