[package]
name    = "randstat-suite-full"
version.workspace = true
edition.workspace = true

[lib]
name = "randstat_suite_full"

[dependencies]
randstat-core            = { workspace = true }
randstat-suite-ent       = { workspace = true }
randstat-suite-nist      = { workspace = true }
randstat-suite-sp800-90b = { workspace = true }
randstat-suite-ais31     = { workspace = true }
randstat-suite-dieharder = { workspace = true }
randstat-suite-testu01   = { workspace = true }
randstat-suite-practrand = { workspace = true }
randstat-suite-gjrand    = { workspace = true }
